2024-12-05 11:24:08.173 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 11:24:22.172 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 11:46:02.637 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 11:51:39.704 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 11:53:33.303 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 11:53:35.302 | ERROR    | utils.ClientLogManager:log:49 - Loop Failed! Error: etcd connection failed, occurred on line 32 in file /usr/local/lib/python3.8/dist-packages/etcd3/client.py
2024-12-05 16:02:18.581 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:19.658 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:20.736 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:21.841 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:22.921 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:24.002 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7ff7a9a38a90> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:46.729 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f8a70b9f820> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:47.808 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f8a70b9f820> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:48.886 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f8a70b9f820> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:02:49.963 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f8a70b9f820> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:07:02.110 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f57a824cc10> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:07:03.188 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f57a824cc10> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:07:04.266 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f57a824cc10> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
2024-12-05 16:07:05.345 | ERROR    | utils.ClientLogManager:log:49 - <utils.node_utils.Subscriber.Subscriber object at 0x7f57a824cc10> calc failed! Error: Invalid argument, occurred on line 75 in file /home/mark/TnTeQAQ/workspace/dpg demo/TBK-Client/utils/DataProcessor.py
